### PR TITLE
corrected moudles

### PR DESCRIPTION
**Pull request by danchitnis**
Hi 👋
You need to upload your source with the npm module, so that esm bundlers can directly access the source rather than already bundled code. I changed back the `package.module` to the `src/index` and removed `/src` from `.npmignore`

Also, you need to decide whether you want normal export or default export for `create`. I think the bundlers will get confused since you have both. I didn't make any changes there since it will break rest of your code.

### CODE REVIEW

**Comment by suren-atoyan** [comment]
Hi @danchitnis 

Thank you for your corrections. I remember I had some issues related to the export types and possible module systems that can be used amd/commonjs/esm. I'll investigate that question and will make corrections.

BTW; I merged your PR and published a new version - v1.0.3

Thank you for your support!

**Comment by suren-atoyan** [comment]
Ah, maybe it was related to CDN

**Comment by suren-atoyan** [comment]
@danchitnis it leads to some unsuspected issues with Next.js. [Here](https://github.com/suren-atoyan/state-local/issues/3) it is. I reverted your changes for a while, to understand what's the problems.

**Comment by danchitnis** [comment]
@suren-atoyan I looked into your [webpack.config.js](https://github.com/suren-atoyan/state-local/blob/master/webpack.config.js) and you are only exporting in UMD, so there is no esm module for `package.modules`. I don't know how to this with webpack, but I can do in Rollup. Few more things:

- keep the `src` folder in your npm
- keep your `dist` folder on github
- Rollup would not work with both export default and export { }. I suggest using `export default create`

It is going to be difficult to cover all combinations, but ES6 is covered now by [93%](https://caniuse.com/es6-module) of the browsers. Unless you are concerned about the remaining 8% 😅

**Comment by suren-atoyan** [comment]
Hello @danchitnis 

Thanks for the notes. I've changed bundling logic, now, the library will have cjs/es/umd bundles. Something like this:

Screen Shot 2021-01-03 at 20 42 33

And the package.json will look like this:

Screen Shot 2021-01-03 at 20 42 45

I'll publish the new version today.

**Comment by suren-atoyan** [comment]
It's already published, check please `v1.0.6`

**Comment by danchitnis** [comment]
Few weeks ago Chrome's team presented an interesting [talk](https://www.youtube.com/watch?v=cLxNdLK--yI) regarding this issue. However, their solution is different with this. They suggest `export` instead. (I am not familiar with this myself). Also it depends slightly if you are targeting the server community or the browser community.

**Comment by suren-atoyan** [comment]
Hmmm, an interesting talk, thank you for sharing. I'll take this approach into account.

**Pull request merged**
